services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobility-payments
    ports:
      - 5432:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
